//
//  Oracle.swift
//  MTRX — Oracle
//
//  Private intelligence layer. Background analysis that never surfaces directly to the user.
//  Feeds insights to Trinity and Morpheus.
//

import Foundation
import Combine

// MARK: - Oracle Insight

/// An insight generated by Oracle's background analysis.
/// Never shown directly to the user — consumed by Trinity and Morpheus.
struct OracleInsight: Identifiable, Sendable {
    let id: UUID
    let type: InsightType
    let category: InsightCategory
    let content: String
    let confidence: Double
    let priority: InsightPriority
    let generatedAt: Date
    let expiresAt: Date?
    let metadata: [String: String]
    let sourceAnalysis: String

    init(
        id: UUID = UUID(),
        type: InsightType,
        category: InsightCategory,
        content: String,
        confidence: Double,
        priority: InsightPriority = .normal,
        expiresAt: Date? = nil,
        metadata: [String: String] = [:],
        sourceAnalysis: String = ""
    ) {
        self.id = id
        self.type = type
        self.category = category
        self.content = content
        self.confidence = confidence
        self.priority = priority
        self.generatedAt = Date()
        self.expiresAt = expiresAt
        self.metadata = metadata
        self.sourceAnalysis = sourceAnalysis
    }
}

// MARK: - Insight Types

enum InsightType: String, Sendable, CaseIterable {
    case pattern          // Detected behavioral or market pattern
    case anomaly          // Anomalous data point
    case prediction       // Forward-looking prediction
    case correlation      // Cross-feed correlation
    case threat           // Potential threat or risk
    case opportunity      // Potential opportunity
    case recommendation   // Strategic recommendation
}

enum InsightCategory: String, Sendable, CaseIterable {
    case market
    case portfolio
    case security
    case behavioral
    case regulatory
    case technical
}

enum InsightPriority: Int, Sendable, Comparable {
    case low = 0
    case normal = 1
    case high = 2
    case critical = 3

    static func < (lhs: InsightPriority, rhs: InsightPriority) -> Bool {
        lhs.rawValue < rhs.rawValue
    }
}

// MARK: - Oracle

/// Private intelligence layer that runs continuous background analysis.
/// Oracle never surfaces information directly to the user — it feeds
/// processed insights to Trinity (for conversation) and Morpheus (for alerts).
final class Oracle {

    // MARK: - Properties

    private let patternIntelligence: PatternIntelligence
    private let probabilityArchitecture: ProbabilityArchitecture
    private let strategicForesight: StrategicForesight
    private let coordinationIntelligence: CoordinationIntelligence
    private let threatDetection: ThreatDetection
    private let dardanAdvisory: DardanAdvisory

    private var activeInsights: [OracleInsight] = []
    private var isRunning: Bool = false
    private var analysisTask: Task<Void, Never>?
    private let analysisInterval: TimeInterval = 60.0 // seconds

    /// Publisher for new insights — consumed by Trinity and Morpheus.
    private let insightSubject = PassthroughSubject<OracleInsight, Never>()
    var insightPublisher: AnyPublisher<OracleInsight, Never> {
        insightSubject.eraseToAnyPublisher()
    }

    /// Publisher for insights specifically for Morpheus trigger evaluation.
    private let morpheusSubject = PassthroughSubject<OracleInsight, Never>()
    var morpheusInsightPublisher: AnyPublisher<OracleInsight, Never> {
        morpheusSubject.eraseToAnyPublisher()
    }

    // MARK: - Initialization

    init(
        patternIntelligence: PatternIntelligence = PatternIntelligence(),
        probabilityArchitecture: ProbabilityArchitecture = ProbabilityArchitecture(),
        strategicForesight: StrategicForesight = StrategicForesight(),
        coordinationIntelligence: CoordinationIntelligence = CoordinationIntelligence(),
        threatDetection: ThreatDetection = ThreatDetection(),
        dardanAdvisory: DardanAdvisory = DardanAdvisory()
    ) {
        self.patternIntelligence = patternIntelligence
        self.probabilityArchitecture = probabilityArchitecture
        self.strategicForesight = strategicForesight
        self.coordinationIntelligence = coordinationIntelligence
        self.threatDetection = threatDetection
        self.dardanAdvisory = dardanAdvisory
    }

    // MARK: - Lifecycle

    /// Start Oracle's background analysis engine.
    func start() {
        guard !isRunning else { return }
        isRunning = true

        analysisTask = Task { [weak self] in
            while !Task.isCancelled {
                await self?.runAnalysisCycle()
                try? await Task.sleep(nanoseconds: UInt64(self?.analysisInterval ?? 60) * 1_000_000_000)
            }
        }
    }

    /// Stop Oracle's background analysis.
    func stop() {
        isRunning = false
        analysisTask?.cancel()
        analysisTask = nil
    }

    // MARK: - Analysis Cycle

    /// Run a single analysis cycle across all intelligence modules.
    private func runAnalysisCycle() async {
        // Run all analysis modules concurrently
        async let patterns = patternIntelligence.analyze()
        async let threats = threatDetection.scan()
        async let predictions = probabilityArchitecture.updateModels()
        async let foresight = strategicForesight.generateScenarios()

        // Collect insights from all modules
        let patternInsights = await patterns
        let threatInsights = await threats
        let predictionInsights = await predictions
        let foresightInsights = await foresight

        var allInsights: [OracleInsight] = []
        allInsights.append(contentsOf: patternInsights)
        allInsights.append(contentsOf: threatInsights)
        allInsights.append(contentsOf: predictionInsights)
        allInsights.append(contentsOf: foresightInsights)

        // Coordinate insights to prevent conflicts
        let coordinated = await coordinationIntelligence.coordinate(allInsights)

        // Distribute insights
        for insight in coordinated {
            activeInsights.append(insight)
            insightSubject.send(insight)

            // Route high-priority or threat insights to Morpheus
            if insight.priority >= .high || insight.type == .threat {
                morpheusSubject.send(insight)
            }
        }

        // Generate Dardan advisory briefing if needed
        await dardanAdvisory.evaluateForBriefing(insights: coordinated)

        // Prune expired insights
        pruneExpiredInsights()
    }

    // MARK: - Insight Queries

    /// Get the latest insights for Trinity to use in conversation.
    /// - Parameter category: Optional category filter.
    /// - Returns: Relevant active insights.
    func latestInsights(category: InsightCategory? = nil) -> [OracleInsight] {
        var filtered = activeInsights
        if let category = category {
            filtered = filtered.filter { $0.category == category }
        }
        return filtered.sorted { $0.priority > $1.priority }
    }

    /// Get insights relevant to a specific topic.
    /// - Parameter topic: The topic to query for.
    /// - Returns: Relevant insights.
    func insights(for topic: String) -> [OracleInsight] {
        // TODO: Implement semantic relevance matching
        activeInsights.filter { $0.content.lowercased().contains(topic.lowercased()) }
    }

    // MARK: - Private Helpers

    private func pruneExpiredInsights() {
        let now = Date()
        activeInsights.removeAll { insight in
            if let expiry = insight.expiresAt, expiry < now {
                return true
            }
            return false
        }

        // Cap total active insights
        if activeInsights.count > 500 {
            activeInsights = Array(activeInsights.suffix(500))
        }
    }
}
